index:
  path: /
  controller: App\Controller\HomeController::index

home:
  path: /home
  controller: App\Controller\HomeController::home

register:
  path: /register/
  controller: App\Controller\RegisterController::register

login:
  path: /login/
  controller: App\Controller\LoginController::login
errorPage:
  path: /error/
  controller: App\Controller\ErrorPageController:main
newMeeting:
  path: /meeting/new/
  controller: App\Controller\MeetingControler:createMeeting
newBill:
  path: /bill/new/
  controller: App\Controller\BillController:newBill

listBills:
  path: /bill/list/
  controller: App\Controller\BillController:listBills

editBill:
  path: /bill/edit/{id}
  controller: App\Controller\BillController::editBill

deleteBill:
  path: /bill/delete/{id}
  controller: App\Controller\BillController:deleteBill

payBill:
  path: /bill/pay/{id}
  controller: App\Controller\BillController:payBill

logout:
  path: /logout/
  controller: App\Controller\LogoutController:main

addEmployee:
  path: /employee/add/
  controller: App\Controller\EmployeeController::add

listEmployees:
  path: /employee/list/
  controller: App\Controller\EmployeeController::listEmployees

editEmployees:
  path: /employee/edit/{id}
  controller: App\Controller\EmployeeController::editEmployee

deleteEmployees:
  path: /employee/delete/{id}
  controller: App\Controller\EmployeeController:deleteEmployee

addCompany:
  path: /company/add/
  controller: App\Controller\CompanyController:add

listCompanies:
  path: /company/list/
  controller: App\Controller\CompanyController:listCompanies

editCompanies:
  path: /company/edit/{id}
  controller: App\Controller\CompanyController:editCompany

deleteCompanies:
  path: /company/delete{id}
  controller: App\Controller\CompanyController:deleteCompany
addCustomer:
  path: /customer/add/
  controller: App\Controller\CustomerController:add

listCustomers:
  path: /customer/list/
  controller: App\Controller\CustomerController:listCustomers

editCustomers:
  path: /customer/edit/{id}
  controller: App\Controller\CustomerController:editCustomer

deleteCustomers:
  path: /customer/delete{id}
  controller: App\Controller\CustomerController:deleteCustomer

newMail:
  path: /mail/new/
  controller: App\Controller\MailController:newMail

newPdf:
  path: /pdf/new/
  controller: App\Controller\PdfController:newPdf


